//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH_DDDL
    {
        public string MA_ANH_DD { get; set; }
        public string TENANH_DD { get; set; }
        public string DD_DULICH { get; set; }
    
        public virtual DD_DULICH DD_DULICH1 { get; set; }
    }
}
